* Название
Прогнозирование направления движения цены биржевых инструментов по новостному потоку.

* Авторы
Дробин М., Говоров И., Родионов В. , Акхиаров В., Борисов А., Мухитдинова С.

МФТИ(ГУ)

* Аннотация
В работе рассматривается задача классификации временных рядов. А именно, по данным о котировках(дата, время, цена, объем)
(с интервалом в один тик) нескольких акций (GAZP, SBER, VTBR, LKOH) за 2 квартал 2017 года с [[https://www.finam.ru/][брокерского сайта]], а
также по экономическим новостям за 2 квартал 2017 года, которые предоставила компания [[http://www.forecsys.ru/][Форексис]], предсказать направление изменение
цены акции(UP, DOWN, STAY). Для решения предлагается использовать тематическое моделирование(ARTM) для создания
фичей из новостей и ансамбль из алгоритмов NMF голосованием большинства, как самый эффективный алгоритм для этой задачи(см статью 4.)

Отличительная особенность работы - применение [[http://www.machinelearning.ru/wiki/images/1/11/Usmanova2018CCM_PLS.pdf][cходящегося перекрестного отображения]] для обоснования связи временных рядов.
 
* Ключевые слова
метрическая классификация, анализ текстов, классификация временных рядов

* Литература:
1. Usmanova K.R., Kudiyarov S.P., Martyshkin R.V., Zamkovoy A.A., Strijov V.V. Analysis of relationships between indicators in forecasting cargo transportation // Systems and Means of Informatics, 2018, 28(3).
2. Kuznetsov M.P., Motrenko A.P., Kuznetsova M.V., Strijov V.V. Methods for intrinsic plagiarism detection and author diarization // Working Notes of CLEF, 2016, 1609 : 912-919.
3. Айсина Роза Мунеровна, Тематическое моделирование финансовых потоков корпоративных клиентов банка по транзакционным данным, выпускная квалификационная работа.
4. [[https://nlp.stanford.edu/pubs/lrec2014-stock.pdf][Lee, Heeyoung, et al. "On the Importance of Text Analysis for Stock Price Prediction." LREC. 2014.]]
